"""Restore the hash-verified source delivery; never extract links or workflows."""
import base64
import hashlib
import io
import json
import lzma
from pathlib import Path, PurePosixPath
import tarfile

root = Path.cwd().resolve()
manifest = json.loads((root / '.import/manifest.json').read_text())
payload = ''.join((root / f'.import/part-{i:02d}.b64').read_text() for i in range(manifest['parts']))
compressed = base64.b64decode(payload, validate=True)
assert hashlib.sha256(compressed).hexdigest() == manifest['sha256'], 'Source payload hash mismatch'
files = []
with tarfile.open(fileobj=io.BytesIO(lzma.decompress(compressed)), mode='r:') as archive:
    for member in archive.getmembers():
        name = PurePosixPath(member.name)
        assert member.isfile() and not name.is_absolute() and '..' not in name.parts
        assert name.parts and name.parts[0] not in ('.git', '.import')
        data = archive.extractfile(member).read()
        data.decode('utf-8')
        files.append({'path': str(name), 'sha256': hashlib.sha256(data).hexdigest(), 'bytes': len(data)})
        if name.parts[0] == '.github':
            continue  # Workflows are explicitly committed by the repository owner connection.
        destination = root.joinpath(*name.parts)
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(data)
assert len(files) == 74, f'Unexpected source file count: {len(files)}'
(root / 'docs/ORIGINAL_RELEASE_MANIFEST.json').write_bytes((root / 'release-manifest.json').read_bytes())
(root / 'docs/SOURCE_IMPORT.json').write_text(json.dumps({**manifest, 'files': files, 'note': 'Sources restored byte-for-byte except CI configuration. Built distributions, package tarballs, sample projects and browser images/video are regenerated by GitHub Actions.'}, indent=2) + '\n')
print(f'Restored {len(files)} verified source entries')
