import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('..', import.meta.url));
const names = ['core', 'pigments', 'paper', 'brushes', 'kernels', 'simulation', 'renderer', 'document', 'ui', 'demo', 'app'];
const modules = new Map(names.map(name => [`@pigmentlab/${name}`, name === 'demo' ? 'app/demo.js' : name === 'app' ? 'app/main.js' : `packages/${name}/src/index.js`]));
const built = new Set(), chunks = [];
async function compile(name) {
    if (built.has(name))
        return;
    const filename = modules.get(name);
    if (!filename)
        throw new Error(`Unmapped module ${name}`);
    let source = await fs.readFile(path.join(root, filename), 'utf8');
    const imports = [...source.matchAll(/import\s*\{([^}]+)\}\s*from\s*['"]([^'"]+)['"];?/g)];
    for (const match of imports)
        await compile(match[2]);
    source = source.replace(/import\s*\{([^}]+)\}\s*from\s*['"]([^'"]+)['"];?/g, (_, bindings, dependency) => `const {${bindings.replace(/\s+as\s+/g, ':')}} = modules[${JSON.stringify(dependency)}];`);
    const exports = [...source.matchAll(/export\s+(?:async\s+)?(?:const|let|function|class)\s+([\w$]+)/g)].map(match => match[1]);
    source = source.replace(/export\s+(?=(?:async\s+)?(?:const|let|function|class)\s)/g, '');
    chunks.push(`\n// ${filename}\nmodules[${JSON.stringify(name)}] = (() => {\n${source}\nreturn Object.freeze({${exports.join(',')}});\n})();\n`);
    built.add(name);
}
await compile('@pigmentlab/app');
const js = `/* PigmentLab 1.0 · MIT · Original implementation · Generated by scripts/build.mjs */\n(() => {\n'use strict';\nconst modules = Object.create(null);\n${chunks.join('\n')}\nwindow.PigmentLab.packages = Object.freeze(modules);\n})();\n`;
const css = await fs.readFile(path.join(root, 'packages/ui/src/studio.css'), 'utf8');
let html = await fs.readFile(path.join(root, 'index.html'), 'utf8');
html = html.replace(/<link rel="stylesheet"[^>]+>/, () => `<style>${css}</style>`).replace(/<script type="importmap">[\s\S]*?<\/script>/, '').replace(/<script type="module">[\s\S]*?<\/script>/, () => `<script>${js.replace(/<\/script/gi, '<\\/script')}</script>`);
await fs.mkdir(path.join(root, 'dist'), { recursive: true });
await fs.writeFile(path.join(root, 'dist/index.html'), html);
await fs.writeFile(path.join(root, 'dist/PigmentLab.html'), html);
await fs.writeFile(path.join(root, 'dist/pigmentlab.js'), js);
await fs.writeFile(path.join(root, 'dist/style.css'), css);
console.log(`Built ${modules.size} modules. Standalone HTML: ${(Buffer.byteLength(html) / 1024).toFixed(1)} KiB. No runtime dependencies.`);
